INSERT INTO Usuario (id, username, password, consejero) VALUES (1, 'admin', '{bcrypt}$2a$10$ps6QN4cRlMvAZmkkBTygyOTrZAjT1Osxs7M4ElwdcOkEAqmO376Be', true);
INSERT INTO Usuario (id, username, password, consejero) VALUES (2, 'user', '{bcrypt}$2a$10$8FLnEJGxM7Iz4IpcoyPq.u5uCnVDxmUpi4lhb2c0gLK8ZNqIB4/4G', false);

INSERT INTO Hermandad (id, nombre, dia) VALUES (1, 'El Amor', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (2, 'Los Despojos', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (3, 'La Paz', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (4, 'La Cena', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (5, 'La Hiniesta', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (6, 'San Roque', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (7, 'La Estrella', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (8, 'La Amargura', 'Domingo de Ramos');
INSERT INTO Hermandad (id, nombre, dia) VALUES (9, 'San Pablo', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (10, 'La Redención', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (11, 'Santa Genoveva', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (12, 'Santa Marta', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (13, 'San Gonzalo', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (14, 'Vera Cruz', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (15, 'Las Penas', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (16, 'Las Aguas', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (17, 'El Museo', 'Lunes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (18, 'El Cerro', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (19, 'San Esteban', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (20, 'La Candelaria', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (21, 'San Benito', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (22, 'La Bofetá', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (23, 'Los Javieres', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (24, 'Los Estudiantes', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (25, 'Santa Cruz', 'Martes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (26, 'El Carmen', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (27, 'El Buen Fin', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (28, 'La Sed', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (29, 'San Bernardo', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (30, 'La Lanzada', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (31, 'El Baratillo', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (32, 'Los Panaderos', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (33, 'Las Siete Palabras', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (34, 'El Cristo de Burgos', 'Miércoles Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (35, 'Los Negritos', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (36, 'Las Cigarreras', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (37, 'La Exaltación', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (38, 'El Valle', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (39, 'Montesión', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (40, 'La Quinta Angustia', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (41, 'Pasión', 'Jueves Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (42, 'El Silencio', 'Madrugá');
INSERT INTO Hermandad (id, nombre, dia) VALUES (43, 'El Gran Poder', 'Madrugá');
INSERT INTO Hermandad (id, nombre, dia) VALUES (44, 'La Macarena', 'Madrugá');
INSERT INTO Hermandad (id, nombre, dia) VALUES (45, 'El Calvario', 'Madrugá');
INSERT INTO Hermandad (id, nombre, dia) VALUES (46, 'La Esperanza de Triana', 'Madrugá');
INSERT INTO Hermandad (id, nombre, dia) VALUES (47, 'Los Gitanos', 'Madrugá');
INSERT INTO Hermandad (id, nombre, dia) VALUES (48, 'La Carreteria', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (49, 'San Buenaventura', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (50, 'El Cachorro', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (51, 'La O', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (52, 'San Isidoro', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (53, 'Montserrat', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (54, 'La Mortaja', 'Viernes Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (55, 'El Sol', 'Sábado Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (56, 'Los Servitas', 'Sábado Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (57, 'La Trinidad', 'Sábado Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (58, 'El Santo Entierro', 'Sábado Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (59, 'La Soledad', 'Sábado Santo');
INSERT INTO Hermandad (id, nombre, dia) VALUES (60, 'La Resurrección', 'Domingo de Resurrección');

INSERT INTO Propietario (id, dni, nombre, apellidos, hermandad_id) VALUES (1, '89088712Y', 'Francisco', 'Vélez de Luna', 52);
INSERT INTO Propietario (id, dni, nombre, apellidos, hermandad_id) VALUES (2, '21135681S', 'Antonio', 'Martínez López', 40);

INSERT INTO Sector (id, localizacion, precio) VALUES (1, 'Campana', 299);
INSERT INTO Sector (id, localizacion, precio) VALUES (2, 'Sierpes', 249);
INSERT INTO Sector (id, localizacion, precio) VALUES (3, 'Plaza de San Francisco', 1099);
INSERT INTO Sector (id, localizacion, precio) VALUES (4, 'Avenida', 199);
INSERT INTO Sector (id, localizacion, precio) VALUES (5, 'Catedral', 149);
INSERT INTO Sector (id, localizacion, precio) VALUES (6, 'Plaza Virgen de los Reyes', 289);

ALTER SEQUENCE hibernate_sequence RESTART WITH 1000;
